### ISSUE TITLE
Issue with Web applications with ParaView & trame

### ISSUE THREAD

**Issue by abhishekchitwar** [Kitware/paraview-trame-components#7]
Trying to understand the parallel post-processing with ParaView and trame as web app. However, facing following issue.

`Reference`
```
https://www.kitware.com/exposing-web-application-with-paraview-5-13-is-getting-simpler/
```

```
ParaView is using venv: .venv
Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.24090\bin\lib\site-packages\paraview\__init__.py", line 217, in <module>
    from .modules import vtkRemotingCore
ImportError: Failed to load vtkRemotingCore: No module named paraview.modules.vtkRemotingClientServerStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.24090\bin\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\ParaView 5.13.24090\bin\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\Research\trame-app\paraview_poc\.venv\Lib\site-packages\ptc\__init__.py", line 2, in <module>
    from .colors import ColorBy  # noqa: F401
  File "D:\Research\trame-app\paraview_poc\.venv\Lib\site-packages\ptc\colors.py", line 1, in <module>
    from paraview import simple
  File "C:\Program Files\ParaView 5.13.24090\bin\lib\site-packages\paraview\__init__.py", line 219, in <module>
    import _paraview_modules_static
ModuleNotFoundError: No module named '_paraview_modules_static'

``` 

Using latest nightly build of ParaView and Python 3.10.10

Appreciate guidance in this regard!

**Comment by jourdain** [comment]
Can you try with the release instead of nightly?

**Comment by abhishekchitwar** [comment]
Still issue persists!

```
mpiexec -n 4 pvbatch --venv .venv -m ptc.apps.sphere
ParaView is using venv: .venv
Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.0\bin\Lib\site-packages\paraview\__init__.py", line 217, in <module>
    from .modules import vtkRemotingCore
ImportError: Failed to load vtkRemotingCore: No module named paraview.modules.vtkRemotingClientServerStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.0\bin\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\ParaView 5.13.0\bin\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\Research\trame-app\paraview_poc\.venv\Lib\site-packages\ptc\__init__.py", line 2, in <module>
    from .colors import ColorBy  # noqa: F401
  File "D:\Research\trame-app\paraview_poc\.venv\Lib\site-packages\ptc\colors.py", line 1, in <module>
    from paraview import simple
  File "C:\Program Files\ParaView 5.13.0\bin\Lib\site-packages\paraview\__init__.py", line 219, in <module>
    import _paraview_modules_static
ModuleNotFoundError: No module named '_paraview_modules_static'
ParaView is using venv: .venv
ParaView is using venv: .venv
ParaView is using venv: .venv
```

**Comment by jourdain** [comment]
Are you using the mpi from ParaView? Also try to pass a full path for the venv as I'm not sure how it get interpreted when processed via mpi.

**Comment by abhishekchitwar** [comment]
Using following MPI 

```
mpiexec
Microsoft MPI Startup Program [Version 10.1.12498.52]
```

```
mpiexec -n 4 pvbatch --venv D:/Research/trame-app/paraview/.venv -m ptc.apps.sphere
ParaView is using venv: D:/Research/trame-app/paraview/.venv
Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.0\bin\Lib\site-packages\paraview\__init__.py", line 217, in <module>
    from .modules import vtkRemotingCore
ImportError: Failed to load vtkRemotingCore: No module named paraview.modules.vtkRemotingClientServerStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.0\bin\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\ParaView 5.13.0\bin\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\Research\trame-app\paraview_poc\.venv\Lib\site-packages\ptc\__init__.py", line 2, in <module>
    from .colors import ColorBy  # noqa: F401
  File "D:\Research\trame-app\paraview_poc\.venv\Lib\site-packages\ptc\colors.py", line 1, in <module>
    from paraview import simple
  File "C:\Program Files\ParaView 5.13.0\bin\Lib\site-packages\paraview\__init__.py", line 219, in <module>
    import _paraview_modules_static
ModuleNotFoundError: No module named '_paraview_modules_static'
ParaView is using venv: D:/Research/trame-app/paraview/.venv
ParaView is using venv: D:/Research/trame-app/paraview/.venv
ParaView is using venv: D:/Research/trame-app/paraview/.venv

```

**Comment by jourdain** [comment]
I mean that `mpiexec` should come from inside `C:\Program Files\ParaView 5.13.0\bin`.

**Comment by abhishekchitwar** [comment]
Installed following version `ParaView-5.13.0-MPI-Windows-Python3.10-msvc2017-AMD64.msi`. I didn't find the `mpiexec` with mentioned path.

**Comment by cquammen** [comment]
> Installed following version ParaView-5.13.0-MPI-Windows-Python3.10-msvc2017-AMD64.msi. I didn't find the mpiexec with mentioned path.

Indeed, on Windows, `mpiexec` is installed when you install MS-MPI. It should be in `C:\Program Files\Microsoft MPI\Bin`.

**Comment by cquammen** [comment]
I was able to start this example on my Windows machine with `ParaView-5.13.0-MPI-Windows-Python3.10-msvc2017-AMD64.msi` installed, so it _should_ work.

The fact that you are seeing `ParaView is using venv: D:/Research/trame-app/paraview/.venv` 4 times suggests that you might be using a version of ParaView for Windows that does NOT support MPI. That message should appear only once. What does your `PATH` environment variable say? Is there a chance that there is another `pvbatch` being found?

Another suggestion: let's try without `mpiexec` for the moment. Can you run `pvbatch --venv D:/Research/trame-app/paraview/.venv -m ptc.apps.sphere` and see if a non-MPI version runs?

**Comment by abhishekchitwar** [comment]
Not sure what's going wrong, I have checked the env, only one version is set to path `C:\Program Files\ParaView 5.13.0\bin\`

```

D:\Research\trame-app\paraview_poc>pvbatch --venv .venv -m ptc.apps.sphere                                
ParaView is using venv: .venv
Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.0\bin\Lib\site-packages\paraview\__init__.py", line 217, in <module>
    from .modules import vtkRemotingCore
ImportError: Failed to load vtkRemotingCore: No module named paraview.modules.vtkRemotingClientServerStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.0\bin\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\ParaView 5.13.0\bin\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\Research\trame-app\paraview_poc\.venv\Lib\site-packages\ptc\__init__.py", line 2, in <module>   
    from .colors import ColorBy  # noqa: F401
  File "D:\Research\trame-app\paraview_poc\.venv\Lib\site-packages\ptc\colors.py", line 1, in <module>     
    from paraview import simple
  File "C:\Program Files\ParaView 5.13.0\bin\Lib\site-packages\paraview\__init__.py", line 219, in <module>
    import _paraview_modules_static
ModuleNotFoundError: No module named '_paraview_modules_static'
```

**Comment by jourdain** [comment]
can you try running `C:\Program Files\ParaView 5.13.0\bin\pvbatch.exe` instead of plain `pvbatch`?

**Comment by abhishekchitwar** [comment]
Getting following O/P 
```
D:\Research\trame-app\paraview_poc>"C:\Program Files\ParaView 5.13.0\bin\pvbatch.exe"
(   0.046s) [pvbatch         ]             pvpython.h:115    ERR| No script specified. Please specify a batch script or use 'pvpython'.

```

**Comment by jourdain** [comment]
Just to be clear the full command line should be

```
mpiexec -n 4  "C:\Program Files\ParaView 5.13.0\bin\pvbatch.exe" --venv "D:/Research/trame-app/paraview/.venv" -m ptc.apps.sphere
```

**Comment by abhishekchitwar** [comment]
Sorry! No! I think, need to reinstall it, still same O/P

```
mpiexec -n 4  "C:\Program Files\ParaView 5.13.0\bin\pvbatch.exe" --venv .venv -m ptc.apps.sphere                
ParaView is using venv: .venv
Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.0\bin\Lib\site-packages\paraview\__init__.py", line 217, in <module>
    from .modules import vtkRemotingCore
ImportError: Failed to load vtkRemotingCore: No module named paraview.modules.vtkRemotingClientServerStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.13.0\bin\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\ParaView 5.13.0\bin\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\Research\trame-app\paraview_poc\.venv\Lib\site-packages\ptc\__init__.py", line 2, in <module>   
    from .colors import ColorBy  # noqa: F401
  File "D:\Research\trame-app\paraview_poc\.venv\Lib\site-packages\ptc\colors.py", line 1, in <module>     
    from paraview import simple
  File "C:\Program Files\ParaView 5.13.0\bin\Lib\site-packages\paraview\__init__.py", line 219, in <module>
    import _paraview_modules_static
ModuleNotFoundError: No module named '_paraview_modules_static'
ParaView is using venv: .venv
ParaView is using venv: .venv
ParaView is using venv: .venv

```

**Comment by jourdain** [comment]
Just out of curiosity, your venv has been built with Python 3.10?

**Comment by abhishekchitwar** [comment]
Thank you, @jourdain and @cquammen, for your guidance. I can now run the program as expected. To achieve this, I recreated the virtual environment and only installed the `paraview-trame-components` module. It appears there was a conflict with other modules I had installed in the virtual environment, which are: but need to check specifically.

https://github.com/ansys/pyfluent-visualization
https://github.com/ansys/pydpf-core


```
D:\Research\trame-app\paraview_poc>mpiexec -n 4 pvbatch --venv .venv -m ptc.apps.sphere
ParaView is using venv: .venv
VisRTX 0.1.6, using devices: 
 0: NVIDIA RTX A2000 Laptop GPU (Total: 4.3 GB, Available: 3.4 GB)
```
![image](https://github.com/user-attachments/assets/e09e6d8e-9454-4a3c-9d56-c7ebabe0d5a1)

**Comment by jourdain** [comment]
Probably vtk was conflicting with ParaView's VTK.
